name: Release Extension to Marketplace
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package Extension
        run: vsce package

      - name: Upload VSIX file
        uses: actions/upload-artifact@v4
        with:
          name: cue-${{ github.ref_name }}.vsix
          path: ./cue-*.vsix

      - name: Publish Extension
        env:
          VSCE_PAT: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
        run: vsce publish
